version: "3.8"

services: 
    nginx:
        image: nginx
        container_name: nginx
        restart: always
        ports: 
            - "80:80"
        environment: 
            - TZ=${TZ}
        volumes: 
            - ${APP_PATH}:/usr/share/nginx/html
            - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf
            - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d
            - ${NGINX_LOG_DIR}:/var/log/nginx
        networks: 
            - default

    php71:
        image: fr34kyn01535/php7.1-fpm
        container_name: php71
        restart: always
        ports: 
            - "9501:9000"
        environment: 
            - TZ=${TZ}
        volumes:
            - ${APP_PATH}:/www
            - ${PHP71_CONF_FILE}:/usr/local/etc/php/php.ini
            - ${PHP71_LOG_DIR}:/usr/local/var/log
            - ${DATA_DIR}:/data
        networks: 
            - default
    
    php72:
        image: binhle410/php7.2-fpm
        container_name: php72
        restart: always
        ports: 
            - "9502:9000"
        environment: 
            - TZ=Asia/Shanghai
        volumes:
            - ${APP_PATH}:/www
            - ${PHP72_CONF_FILE}:/usr/local/etc/php/php.ini
            - ${PHP72_LOG_DIR}:/usr/local/var/log
            - ${DATA_DIR}:/data
        networks: 
            - default

    php56:
        image: mikolatero/php5.6-fpm-alpine
        container_name: php56
        restart: always
        ports: 
            - "9503:9000"
        environment: 
            - TZ=${TZ}
        volumes:
            - ${APP_PATH}:/www
            - ${PHP56_CONF_FILE}:/etc/php5/cli/php.ini
            - ${PHP56_LOG_DIR}:/usr/local/var/log
            - ${DATA_DIR}:/data
        networks: 
            - default

networks: 
    default:
